### ISSUE TITLE
Multi-way if's indent still doesn't work correctly

### ISSUE THREAD

**Issue by konn** [nilcons/hi2#12]
Thank you for supporting MultiWayIf! By the way, it cannot handle indentation correctly if the first guard starts at the same line as `if`. Suppose, in the below code: the cursor is placed right after the first `|` (indicated by `^`) below:

``` haskell
main :: IO ()
main = if | True -> undefined
--                 ^ here
          | otherwise -> undefined
```

Then, if I hit `C-j`, `hi2` place the `undefined` as follows:

``` haskell
main :: IO ()
main = if | True ->
  undefined
          | otherwise -> undefined
```

This behaviour is wrong, and GHC claims parse error. `undefined` should be placed on the right to `|`.

**Comment by klao** [comment]
Thank you! I didn't notice this issue while testing yesterday. Fixed.
