### ISSUE TITLE
add hi2 to melpa stable

### ISSUE THREAD

**Issue by joe9** [nilcons/hi2#13]
Hello,

Thank you for making hi2 available.

I use hi2 and like it a lot. I am wondering if you could please add a tag to this repo. Adding a tag to this repo enables hi2 repo to be available to stable melpa.

These are the sample commands to add and push a tag to the repo, if it helps:
git tag 1.0
git tag --list
git push origin 1.0

Thanks  again and Sorry for the bother,
Joe

**Comment by errge** [comment]
Did this.  Thanks for the detailed commands.

Anything else to do on my side to have this in stable melpa?

**Comment by joe9** [comment]
That should be it. Once tagged with a release number, it should automatically be included in melpa-stable.

Thanks
