### ISSUE TITLE
mergin with offical haskell-indentation.el

### ISSUE THREAD

**Issue by kuribas** [nilcons/hi2#7]
I am in favor of merging your version with the official haskell-indentation.el  I think your changes may be beneficial for users of the "offical" version.  Perhaps you could add compatible changes to the official repository, and keep your fork for your work on the parser?

**Comment by errge** [comment]
Yes, I'm being slow on this, as a lot of other things around Haskell came up.

If anyone wants to jump in and help, then managing this merge to go through to haskell-mode would be a big contribution.  If I remember correctly, the agreement with the haskell-mode guys were that we should add this as a new indentation mode and send an announecment that users should test to see if there are any regressions compared to haskell-indentation.

From my point of view, merging your pull request has a much bigger priority, than working on the upstream merge at the moment.  It's unfortunate that I wasn't able to do that either, sorry.
